### ISSUE TITLE
Remove GameLoop Quark

### ISSUE THREAD

**Issue by dathinaios** [supercollider-quarks/downloaded-quarks#1]
My `GameLoop` quark in this repository is outdated. Since it is now available through the new quarks system could you please remove it?

Thanks!

**Comment by crucialfelix** [comment]
I did an update of all the quarks here, so your GameLoop quark should now also be up to date.

This is the actually part of the new quarks system. This downloaded-quarks is just a huge cache file of all quarks.  Most people wouldn't use this, they would use the normal way to downloaded individual quarks.

We just forgot to do a release for 3.8.

**Comment by dathinaios** [comment]
Thanks! :)

But what is the purpose of this repo? And does it have to be kept in sync manually?

**Comment by crucialfelix** [comment]
These are for people who are unable or unwilling to use git. They are kind of a release - a snapshot of the quarks paired up with a supercollider release. So it shouldn't be tightly synced (every time there is a change).
